#!/usr/bin/env python3
"""
Compute migration flux (sigma_mig) from IRS SOI county-to-county migration data.

This script:
1. Reads county-level migration flows from IRS SOI files (2006-2022, excl. 2020)
2. Maps counties to MSAs using CBSA delineation
3. Aggregates county flows to MSA-MSA level
4. Computes migration rate: sigma_mig = gross_migration / ACS_population

Requires: results/msa_pop_2006-2022.csv (generated by compute_eta.py)

Usage:
    python compute_sigma_mig.py

Output:
    results/sigma_mig_2006-2022.csv
"""

import pandas as pd
import numpy as np
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

# Configuration
DATA_DIR = Path("/home/roger/DissipativeUrbanism/geodesic_efficiency/data")
RESULTS_DIR = Path("/home/roger/DissipativeUrbanism/geodesic_efficiency/results")
IRS_DIR = DATA_DIR / "IRS_SOI"

# Create results directory if needed
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# Years for analysis: 2006-2022, excluding 2020
STUDY_YEARS = [y for y in range(2006, 2023) if y != 2020]  # 2006-2019, 2021-2022

# File mapping: Tax year -> file suffix
FILE_MAPPING = {
    # Fixed-width ASCII files (2006-2008)
    2006: ('0506', 'ascii'),
    2007: ('0607', 'ascii'),
    2008: ('0708', 'ascii'),
    # CSV files (2009-2022)
    2009: ('0809', 'csv'),
    2010: ('0910', 'csv'),
    2011: ('1011', 'csv'),
    2012: ('1112', 'csv'),
    2013: ('1213', 'csv'),
    2014: ('1314', 'csv'),
    2015: ('1415', 'csv'),
    2016: ('1516', 'csv'),
    2017: ('1617', 'csv'),
    2018: ('1718', 'csv'),
    2019: ('1819', 'csv'),
    2021: ('2021', 'csv'),
    2022: ('2122', 'csv'),
}


def load_cbsa_delineation():
    """Load official OMB CBSA delineation file."""
    filepath = DATA_DIR / "reference" / "cbsa_county_crosswalk.csv"
    
    if not filepath.exists():
        print(f"  ERROR: CBSA file not found: {filepath}")
        return None
    
    print(f"  Loading: {filepath.name}")
    cbsa = pd.read_csv(filepath)
    
    # Construct full 5-digit county FIPS
    cbsa['county_fips'] = (
        cbsa['State FIPS'].astype(str).str.zfill(2) + 
        cbsa['County FIPS'].astype(str).str.zfill(3)
    )
    
    cbsa = cbsa.rename(columns={
        'CBSA Code': 'cbsa_code',
        'CBSA Title': 'cbsa_title'
    })
    
    cbsa['cbsa_code'] = cbsa['cbsa_code'].astype(str)
    cbsa['county_fips'] = cbsa['county_fips'].astype(str)
    
    print(f"    {len(cbsa)} counties -> {cbsa['cbsa_code'].nunique()} MSAs")
    
    return cbsa[['cbsa_code', 'cbsa_title', 'county_fips']]


def read_ascii_migration_file(filepath, year):
    """Read fixed-width ASCII migration file (2006-2008)."""
    # Column positions based on IRS documentation
    colspecs = [
        (0, 2),    # State_Code_Dest
        (3, 6),    # County_Code_Dest
        (7, 9),    # State_Code_Origin
        (10, 13),  # County_Code_Origin
        (14, 16),  # State_Abbrv
        (17, 47),  # County_Name
        (48, 58),  # Return_Num
        (59, 69),  # Exmpt_Num (PEOPLE)
        (70, 82),  # Aggr_AGI
        (83, 91),  # Mean_AGI
    ]
    
    colnames = [
        'state_dest', 'county_dest', 'state_orig', 'county_orig',
        'state_abbr', 'county_name', 'n1', 'n2', 'agi', 'mean_agi'
    ]
    
    # Try different encodings for ASCII files too
    encodings = ['utf-8', 'latin-1', 'iso-8859-1', 'cp1252']
    df = None
    
    for encoding in encodings:
        try:
            df = pd.read_fwf(filepath, colspecs=colspecs, names=colnames, encoding=encoding)
            break
        except UnicodeDecodeError:
            continue
    
    if df is None:
        raise UnicodeDecodeError(f"Could not read {filepath} with any encoding")
    
    # Construct FIPS codes
    df['dest_fips'] = df['state_dest'].astype(str).str.zfill(2) + df['county_dest'].astype(str).str.zfill(3)
    df['orig_fips'] = df['state_orig'].astype(str).str.zfill(2) + df['county_orig'].astype(str).str.zfill(3)
    
    # Keep only county-to-county flows (exclude summary codes)
    df = df[~df['state_orig'].isin(['96', '97', '98'])].copy()
    
    # Convert to numeric
    df['n2'] = pd.to_numeric(df['n2'], errors='coerce')
    df['agi'] = pd.to_numeric(df['agi'], errors='coerce')
    
    return df[['orig_fips', 'dest_fips', 'n2', 'agi']]


def read_csv_migration_file(filepath, year):
    """Read CSV migration file (2009-2022)."""
    # Try different encodings
    encodings = ['utf-8', 'latin-1', 'iso-8859-1', 'cp1252']
    df = None
    
    for encoding in encodings:
        try:
            df = pd.read_csv(filepath, low_memory=False, encoding=encoding)
            break
        except UnicodeDecodeError:
            continue
    
    if df is None:
        raise UnicodeDecodeError(f"Could not read {filepath} with any encoding")
    
    # Handle different column naming conventions
    # Early files (2009-2011) use y1=origin, y2=destination
    # Later files (2011+) may use y1=origin, y2=destination consistently
    
    if 'y1_statefips' in df.columns:
        # Standard naming
        df['orig_fips'] = df['y1_statefips'].astype(str).str.zfill(2) + df['y1_countyfips'].astype(str).str.zfill(3)
        df['dest_fips'] = df['y2_statefips'].astype(str).str.zfill(2) + df['y2_countyfips'].astype(str).str.zfill(3)
    elif 'State_Code_Origin' in df.columns:
        # Alternative naming
        df['orig_fips'] = df['State_Code_Origin'].astype(str).str.zfill(2) + df['County_Code_Origin'].astype(str).str.zfill(3)
        df['dest_fips'] = df['State_Code_Dest'].astype(str).str.zfill(2) + df['County_Code_Dest'].astype(str).str.zfill(3)
    
    # Keep only county-to-county flows
    df = df[~df['orig_fips'].str.startswith(('96', '97', '98'))].copy()
    
    # Standardize column names
    if 'n2' not in df.columns and 'Exmpt_Num' in df.columns:
        df['n2'] = df['Exmpt_Num']
    if 'agi' not in df.columns and 'Aggr_AGI' in df.columns:
        df['agi'] = df['Aggr_AGI']
    
    # Convert to numeric
    df['n2'] = pd.to_numeric(df['n2'], errors='coerce')
    df['agi'] = pd.to_numeric(df['agi'], errors='coerce')
    
    return df[['orig_fips', 'dest_fips', 'n2', 'agi']]


def load_migration_data(year):
    """Load migration data for a specific year."""
    if year not in FILE_MAPPING:
        return None
    
    suffix, file_type = FILE_MAPPING[year]
    
    # Try to find inflow and outflow files
    inflow_file = None
    outflow_file = None
    
    if file_type == 'ascii':
        inflow_file = IRS_DIR / f"countyinflow{suffix}.dat"
        outflow_file = IRS_DIR / f"countyoutflow{suffix}.dat"
    else:
        inflow_file = IRS_DIR / f"countyinflow{suffix}.csv"
        outflow_file = IRS_DIR / f"countyoutflow{suffix}.csv"
    
    if not inflow_file.exists():
        print(f"    Warning: {inflow_file.name} not found")
        return None
    
    # Read inflow data
    if file_type == 'ascii':
        inflow = read_ascii_migration_file(inflow_file, year)
    else:
        inflow = read_csv_migration_file(inflow_file, year)
    
    return inflow


def aggregate_to_msa_flows(flow_df, cbsa_df, year):
    """Aggregate county flows to MSA-MSA level."""
    # Merge origin counties to MSAs
    flow_msa = flow_df.merge(
        cbsa_df.rename(columns={'county_fips': 'orig_fips', 'cbsa_code': 'orig_cbsa'}),
        on='orig_fips',
        how='left'
    )
    
    # Merge destination counties to MSAs
    flow_msa = flow_msa.merge(
        cbsa_df.rename(columns={'county_fips': 'dest_fips', 'cbsa_code': 'dest_cbsa'}),
        on='dest_fips',
        how='left'
    )
    
    # Keep only INTER-MSA flows (true migration between metropolitan areas)
    # Exclude intra-MSA moves which are internal redistribution
    flow_msa = flow_msa[(flow_msa['orig_cbsa'].notna()) & (flow_msa['dest_cbsa'].notna())]
    flow_msa = flow_msa[flow_msa['orig_cbsa'] != flow_msa['dest_cbsa']]
    
    if len(flow_msa) == 0:
        return pd.DataFrame()
    
    # Aggregate flows (skip NaN values)
    msa_flows = flow_msa.groupby(['orig_cbsa', 'dest_cbsa']).agg({
        'n2': lambda x: x.sum(min_count=1),
        'agi': lambda x: x.sum(min_count=1)
    }).reset_index()
    
    msa_flows['year'] = year
    
    return msa_flows


def load_acs_population():
    """Load MSA population data from ACS (computed by compute_eta.py)."""
    pop_file = RESULTS_DIR / "msa_pop_2006-2022.csv"
    
    if not pop_file.exists():
        print(f"  WARNING: Population file not found: {pop_file}")
        print(f"  Run compute_eta.py first to generate population data.")
        return None
    
    pop_df = pd.read_csv(pop_file)
    
    # Ensure consistent types
    pop_df['cbsa_code'] = pop_df['cbsa_code'].astype(str)
    pop_df['year'] = pop_df['year'].astype(int)
    
    print(f"    Loaded {len(pop_df)} MSA-year population records")
    return pop_df


def compute_sigma_mig(msa_flows_all, pop_df):
    """Compute migration flux sigma_mig time-series for each MSA.
    
    For longitudinal analysis, outputs migration rate at each year t:
    σ_mig(t) = gross_migration(t) / population(t)
    
    where:
    - gross_migration = inflows + outflows (IRS exemptions)
    - population = ACS total population (from compute_eta.py)
    """
    results = []
    
    # Get unique MSAs and ensure string type for matching
    all_cbsas = set(msa_flows_all['orig_cbsa'].unique()) | set(msa_flows_all['dest_cbsa'].unique())
    all_cbsas = set(str(c) for c in all_cbsas)
    
    # Create population lookup dictionary
    if pop_df is not None:
        pop_lookup = {}
        for _, row in pop_df.iterrows():
            pop_lookup[(str(row['cbsa_code']), int(row['year']))] = row['population']
    else:
        pop_lookup = {}
    
    for cbsa_code in all_cbsas:
        for year in STUDY_YEARS:
            if year == 2020:
                continue
                
            year_flows = msa_flows_all[msa_flows_all['year'] == year]
            
            if len(year_flows) == 0:
                continue
            
            # Get flows for this MSA
            inflows = year_flows[year_flows['dest_cbsa'] == cbsa_code]
            outflows = year_flows[year_flows['orig_cbsa'] == cbsa_code]
            
            # Compute GROSS migration (total population turnover volume)
            total_in = inflows['n2'].sum() if len(inflows) > 0 else 0
            total_out = outflows['n2'].sum() if len(outflows) > 0 else 0
            gross_migration = total_in + total_out
            
            # Get population from ACS data
            pop = pop_lookup.get((cbsa_code, year), np.nan)
            
            # Calculate sigma_mig as rate (migration / population)
            if not np.isnan(pop) and pop > 0:
                sigma_mig = gross_migration / pop
            else:
                sigma_mig = np.nan
            
            results.append({
                'cbsa_code': cbsa_code,
                'year': year,
                'sigma_mig': sigma_mig,
                'gross_migration': gross_migration,
                'population': pop,
                'total_in': total_in,
                'total_out': total_out
            })
    
    return pd.DataFrame(results)


def main():
    """Main computation pipeline."""
    print("="*50)
    print("Migration Flux (sigma_mig) - LONGITUDINAL")
    print("="*50)
    print(f"Period: {STUDY_YEARS[0]}-{STUDY_YEARS[-1]} (16 years, excl. 2020)")
    print("\nFormula: sigma_mig = (inflows + outflows) / ACS_population")
    
    # Step 1: Load CBSA delineation
    print("\nStep 1: Loading CBSA delineation...")
    cbsa_df = load_cbsa_delineation()
    if cbsa_df is None:
        print("  ERROR: CBSA file not found!")
        return None
    
    # Step 2: Load migration data for all years
    print("\nStep 2: Loading migration data...")
    all_flows = []
    
    for year in STUDY_YEARS:
        print(f"  Loading {year}...")
        flows = load_migration_data(year)
        
        if flows is not None:
            msa_flows = aggregate_to_msa_flows(flows, cbsa_df, year)
            if len(msa_flows) > 0:
                all_flows.append(msa_flows)
                print(f"    {len(msa_flows)} MSA-MSA flows")
            else:
                print(f"    No valid flows")
        else:
            print(f"    File not found")
    
    if len(all_flows) == 0:
        print("\n  ERROR: No migration data loaded!")
        return None
    
    msa_flows_all = pd.concat(all_flows, ignore_index=True)
    print(f"\n  Total: {len(msa_flows_all)} MSA-MSA flow records")
    
    # Step 3: Load ACS population data
    print("\nStep 3: Loading ACS population data...")
    pop_df = load_acs_population()
    
    # Step 4: Compute sigma_mig time-series
    print("\nStep 4: Computing sigma_mig time-series...")
    print("  Formula: sigma_mig = gross_migration / ACS_population")
    results_df = compute_sigma_mig(msa_flows_all, pop_df)
    
    # Add CBSA titles
    cbsa_titles = cbsa_df[['cbsa_code', 'cbsa_title']].drop_duplicates()
    results_df = results_df.merge(cbsa_titles, on='cbsa_code', how='left')
    
    # Summary by MSA
    msa_summary = results_df.groupby('cbsa_code').agg({
        'sigma_mig': ['mean', 'std', 'count'],
        'cbsa_title': 'first'
    }).reset_index()
    msa_summary.columns = ['cbsa_code', 'sigma_mean', 'sigma_std', 'n_years', 'cbsa_title']
    n_msas = msa_summary['cbsa_code'].nunique()
    
    print(f"\n  Total sigma_mig records: {len(results_df)} MSA-year records")
    print(f"  Unique MSAs: {n_msas}")
    
    # Summary statistics
    # Filter to valid results (with population data)
    valid_results = results_df[results_df['sigma_mig'].notna()].copy()
    
    print(f"\n{'='*50}")
    print("SUMMARY (Longitudinal)")
    print(f"{'='*50}")
    print(f"  MSA-year records: {len(valid_results)} (with ACS population)")
    print(f"  Total records:    {len(results_df)}")
    print(f"  Unique MSAs:      {n_msas}")
    print(f"  Years per MSA:    {len(results_df)/n_msas:.1f} (avg)")
    
    if len(valid_results) > 0:
        print(f"\n  σ_mig (Migration rate = gross_mig / ACS_pop):")
        print(f"    Mean:    {valid_results['sigma_mig'].mean():.4f} ({valid_results['sigma_mig'].mean()*100:.2f}%)")
        print(f"    Median:  {valid_results['sigma_mig'].median():.4f} ({valid_results['sigma_mig'].median()*100:.2f}%)")
        print(f"    Std:     {valid_results['sigma_mig'].std():.4f}")
        print(f"    Range:   [{valid_results['sigma_mig'].min():.4f}, {valid_results['sigma_mig'].max():.4f}]")
    
    # Top MSAs by average migration rate
    if len(valid_results) > 0:
        valid_summary = valid_results.groupby('cbsa_code').agg({
            'sigma_mig': ['mean', 'std', 'count'],
            'cbsa_title': 'first'
        }).reset_index()
        valid_summary.columns = ['cbsa_code', 'sigma_mean', 'sigma_std', 'n_years', 'cbsa_title']
        
        print(f"\n  Top 10 MSAs (highest average migration rate):")
        top_msas = valid_summary.nlargest(10, 'sigma_mean')
        for i, row in top_msas.iterrows():
            name = row['cbsa_title'][:40] if pd.notna(row['cbsa_title']) else 'Unknown'
            print(f"    {name:40s}: {row['sigma_mean']:.4f} ({row['sigma_mean']*100:.2f}%) (n={int(row['n_years'])})")
    
    # Save results
    output_file = RESULTS_DIR / "sigma_mig_2006-2022.csv"
    results_df.to_csv(output_file, index=False)
    print(f"\n  Saved: {output_file.name}")
    
    print(f"\n{'='*50}")
    print("COMPLETE")
    print(f"{'='*50}")
    
    return results_df


if __name__ == "__main__":
    main()
